# Generated by Django 4.0.5 on 2024-12-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railgunapp', '0002_post_background_post_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('qno', models.IntegerField(default=0)),
            ],
        ),
    ]
