# Generated by Django 4.0.5 on 2024-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railgunapp', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
