# Generated by Django 4.0.5 on 2025-01-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railgunapp', '0005_alter_answer_answer_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
